# Main application configuration

# This setting now acts as a switch to select the active broker.
# Change this to "alpaca" when you want to run with the Alpaca broker.
broker:
  name: "alpaca" 

# A new top-level section to hold settings for each specific broker.
brokers:
  oanda:
    # OANDA_API_URL from .env will override this if present.
    base_url: "https://api-fxpractice.oanda.com"

  alpaca:
    # Alpaca's URL for paper trading.
    base_url: "https://paper-api.alpaca.markets"
    # We can add other Alpaca-specific settings here in the future.

# --- The rest of your configuration remains the same ---

webhook_server:
  host: "0.0.0.0"
  port: 5000

trading:
  # NOTE: These instruments are forex pairs for Oanda. When using Alpaca,
  # you will need to change these to stock tickers (e.g., "AAPL", "TSLA").
  allowed_instruments:
    - "AAPL"
    - "TSLA"
    - "GOOGL"

  defaults:
    quantity: 1
    order_type: "MARKET"
    time_in_force: "GTC" 

  instrument_settings:
    EUR_USD:
      default_quantity: 1000
      min_quantity: 10
      max_quantity: 1000000
      default_stop_loss_pips: 20
      default_take_profit_pips: 40
    USD_JPY:
      default_quantity: 1000
      min_quantity: 1
      max_quantity: 1000
      default_stop_loss_pips: 20
      default_take_profit_pips: 40

logging:
  level: "INFO"